version: "3"

services:
    apache:
        build: .docker/apache
        container_name: aos_apache
        ports:
            - "8000:80"
        volumes:
            - .docker/config/vhosts:/etc/apache2/sites-enabled:ro
            - .:/home/wwwroot/aos:rw
        depends_on:
            - php

    mysql:
        image: mysql
        command: "--default-authentication-plugin=mysql_native_password --lower_case_table_names=2"
        container_name: aos_mysql
        volumes:
            - .docker/data/db:/var/lib/mysql:rw
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: phpDb
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        restart: on-failure
        ports:
            - "3306:3306"

    php:
        build: .docker/php
        container_name: aos_php
        volumes:
            - .:/home/wwwroot/aos
            - /home/wwwroot/aos/vendor/
            - ./tmp:/home/wwwroot/tmp:rw
        environment:
            MYSQL_TEST_DATABASE: php-test
            DOCKER: 1
        ports:
            - "9123:9000"
            # - "9003:9003"
        depends_on:
            - mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: aos_phpmyadmin
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
        ports:
            - "8080:80"
        depends_on:
            - mysql
