name: PHPUnit Tests

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      mysql-server:
        image: mysql:5.7
        env:
          # MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: db_name_test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v2

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        id: composer-install
        # if: steps.composer-cache.outputs.cache-hit != 'true'
        run: composer install --prefer-dist --no-progress

      - name: Xdebug Action
        uses: MilesChou/docker-xdebug@master

      - name: Run test suite
        id: phpunit
        env:
          JWT_SECRET: "${{ secrets.JWT_SECRET }}"
          XDEBUG_MODE: "coverage"
        run: |
          echo "${{ secrets.PUBLICA }}" >| ./config/public.pem;
          echo "${{ secrets.PRIVADA }}" >| ./config/private.pem;
          chmod -R +x vendor
          chmod -R +x bin
          bin/phpunit -dxdebug.mode=coverage
          
